apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: whistler-operator
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      app: whistler-operator
  template:
    metadata:
      labels:
        app: whistler-operator
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["kopf", "run", "whistler/operator.py", "--verbose"]
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: USER_VOLUME_ACCESS_MODE
              value: {{ .Values.userVolume.accessMode | quote }}
            - name: USER_VOLUME_SIZE
              value: {{ .Values.userVolume.size | quote }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/etc/whistler-config/volumes.yaml"
              subPath: "volumes.yaml"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config

