apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-operator
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of the namespace & cluster.
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch, create, get, update, patch, delete]

  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [list, watch, create, get, update, patch, delete]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [whistler.example.com]
    resources: [whistlerinstances, whistlertemplates, whistlerinstances/status, whistlertemplates/status]
    verbs: [list, watch, patch, get, update, create, delete]

  # Application: other resources it produces and manages.
  - apiGroups: [""]
    resources: [pods, pods/exec, persistentvolumeclaims, services, events, configmaps, secrets]
    verbs: [create, delete, deletecollection, get, list, patch, update, watch]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [create, delete, deletecollection, get, list, patch, update, watch]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, delete, deletecollection, get, list, patch, update, watch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-operator
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-operator
    namespace: {{ .Release.Namespace }}
