image:
  repository: ghcr.io/marma/whistler
  pullPolicy: IfNotPresent
  tag: "latest"

operator:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 512Mi

server:
  enabled: true
  replicaCount: 1
  service:
    type: NodePort
    port: 8022
    nodePort: 30022
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 2000m
      memory: 1Gi

whistler:
  auth:
    allowAny: false
  users: []
    # - name: someuser
    #   publicKeys:
    #     - "ssh-rsa ..."

  node_selectors:
    - name: GPU type
      key: accelerator
      values:
        - nvidia-tesla-p100
        - A100-SXM4-40GB
    - name: Node name
      key: kubernetes.io/hostname
      values:
        - node_1
        - node_2
templates:
  small:
    description: "Small instance"
    image: "ubuntu:latest"
    resources:
      cpu: 500m
      memory: 2Gi

