apiVersion: whistler.io/v1
kind: WhistlerTemplate
metadata:
  name: small
  namespace: whistler
spec:
  image: ubuntu:latest
  description: "Small Ubuntu instance"
  resources:
    cpu: "500m"
    memory: "2Gi"
